<ul id="post-list">
<?php


$i = 0;
while($i < count($result)){
	echo "<a href='?post&action=view&id=".$result[$i]->getId()."'>";
	echo "<li>";
		echo "<img class='img-post' src='assets/img/".$result[$i]->getImage()."' />";
		echo "<div class='content-post'>";
			echo "<h2>".$result[$i]->getTitle()."</h2>";
			echo "<p>".$result[$i]->getContent()."</p>";
			echo "<p class='date-post'>".$result[$i]->getCreatedAt()."</p>";
		echo "</div>";
	echo "</li>";
	echo "</a>";
	$i++;
}


?>
</ul>
